package TP1;


/**
* TP1/helloWorld.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello-world.idl
* Wednesday, November 17, 2021 10:52:30 AM WET
*/

public interface helloWorld extends helloWorldOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface helloWorld
