package TP1;

/**
* TP1/helloWorldHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello-world.idl
* Wednesday, November 17, 2021 10:52:30 AM WET
*/

public final class helloWorldHolder implements org.omg.CORBA.portable.Streamable
{
  public TP1.helloWorld value = null;

  public helloWorldHolder ()
  {
  }

  public helloWorldHolder (TP1.helloWorld initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TP1.helloWorldHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TP1.helloWorldHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TP1.helloWorldHelper.type ();
  }

}
