package TP1;


/**
* TP1/helloWorldHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello-world.idl
* Wednesday, November 17, 2021 10:52:30 AM WET
*/

abstract public class helloWorldHelper
{
  private static String  _id = "IDL:TP1/helloWorld:1.0";

  public static void insert (org.omg.CORBA.Any a, TP1.helloWorld that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TP1.helloWorld extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TP1.helloWorldHelper.id (), "helloWorld");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TP1.helloWorld read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_helloWorldStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TP1.helloWorld value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TP1.helloWorld narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TP1.helloWorld)
      return (TP1.helloWorld)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TP1._helloWorldStub stub = new TP1._helloWorldStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TP1.helloWorld unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TP1.helloWorld)
      return (TP1.helloWorld)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TP1._helloWorldStub stub = new TP1._helloWorldStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
