package TP1;


/**
* TP1/helloWorldOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello-world.idl
* Wednesday, November 17, 2021 10:52:30 AM WET
*/

public interface helloWorldOperations 
{
  String sayHelloWorld ();
} // interface helloWorldOperations
