package Banque;


/**
* Banque/Compte.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* Wednesday, November 17, 2021 11:17:04 AM WET
*/

public interface Compte extends CompteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Compte
