package Banque;


/**
* Banque/CompteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* Wednesday, November 17, 2021 11:17:04 AM WET
*/

public interface CompteOperations 
{
  float lire_montant ();
  void crediter (float montant);
  void debiter (float montant);
} // interface CompteOperations
